- name: Remove a file, if present
  ansible.windows.win_file:
    path: E:\dummyfile.bin
    state: absent
  ignore_errors: true

# # - name: Restart a service
# #   ansible.windows.win_service:
# #     name: "{{ service }}"
# #     state: restarted

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: "{{service}}"
    state: restarted
  ignore_errors: true

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{dir}}/lixo.img"
    state: absent
  ignore_errors: true