- name: Remove a file, if present
  ansible.windows.win_file:
    path: '{{dir}}\dummyfile.bin'
    state: absent
  ignore_errors: true
  when: so == "windows" and dir is defined

- name: Restart a service
  ansible.windows.win_service:
    name: "{{ service }}"
    state: restarted
  ignore_errors: true
  when: so == "windows" and service is defined

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: "{{service}}"
    state: restarted
  ignore_errors: true
  when: so == "systemd" and service is defined

- name: Remove file (delete file)
  ansible.builtin.file:
    path: "{{dir}}/lixo.img"
    state: absent
  ignore_errors: true
  when: so == "linux" and dir is defined