---
# - hosts: localhost
#   gather_facts: no

#   tasks:

#   - include_role:
#       name: inventory

- name: Teste rulebook
  hosts: "{{server}}"
  gather_facts: no
  vars:
    ansible_connection: ssh

  tasks:

    - include_role:
        name: disk
  
  when: target == "linux"

- name: Teste rulebook
  hosts: "{{server}}"
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_user: lcsilva@LCS.LOCAL
    ansible_winrm_password: 'homelab@1983'
    ansible_winrm_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_read_timeout_sec: 120
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_server_cert_validation: ignore

  tasks:

    - include_role:
        name: disk
  
  when: target == "windows"