- name: Attempt to connect via SSH
  wait_for:
    host: "{{item}}"
    port: 22
    timeout: 3
  ignore_errors: yes
  register: ssh
  with_items: "{{hostname}}"

- name: Attempt to connect via WinRM
  wait_for:
    host: "{{item}}"
    port: 5985
    timeout: 3
  ignore_errors: yes
  register: winrm
  with_items: "{{hostname}}"

- name: Populate Linux hosts group
  add_host:
    name: "{{item.item}}"
    groups: Linux
  when: item.state is defined
  with_items: "{{ssh.results}}"

- name: Populate Windows hosts group
  add_host:
    name: "{{item.item}}"
    groups: Windows
  when: item.state is defined
  with_items: "{{winrm.results}}"