---
- name: Zabbix Test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 192.168.0.254
        port: 5001
        
  rules:
  
    - name: debug
      condition: event.payload is defined
      action:
        debug: