---
- name: Zabbix Test rulebook
  hosts: EDA
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  rules:
    - name: debug
      condition: event.payload
      action:
        debug:

    - name: Alerta de uso acima de 90%
      condition: |
        event.payload.host_host == 'homelab01.lcs.local' and
        (event.payload.operation_data.split(':')[1].strip().rstrip('%') | float) > 90
      action:
        run_job_template:
          name: "My first playbook"
          organization: "default"