---
- name: Zabbix Test rulebook
  hosts: EDA
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5015

  rules:
  
    - name: debug
      condition: event.payload
      action:
        debug: