---
- name: Zabbix Test rulebook
  hosts: EDA
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5010
        timeout: 300
        
  rules:

      # - name: debug
    #   condition: event.payload
    #   action:
    #     debug:  
    #       msg: "Event received: {{ event.payload.event_name }}"

    - name: Motor de regras
      condition: |
        event.payload.host_host == 'homelab03' and
        event.payload.motor-de-regras.service is match("Service is not running", ignorecase=true)
      action:
        run_job_template:
          name: "My first playbook"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"
              service: "{{ event.payload.event_tags.service[0] }}"
