---
- name: Zabbix Test rulebook
  hosts: EDA
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5015

  rules:
    
    - name: Motor de regras
      condition: event.payload.event_name is search("Service is not running", ignorecase=true)
      action:
        run_job_template:
          name: "Orizon"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"
              service: "{{ event.payload.event_name.split(':')[1] | trim }}"
    
    - name: Alerta de uso acima de 90% (Linux)
      condition: event.payload.event_name is search("Space is critically low", ignorecase=true)
      action:
        run_job_template:
          name: "Orizon"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"
              dir: "{{ event.payload.event_tags.filesystem[0] }}"

    - name: Alerta de uso acima de 90% (Windows)
      condition: |
        event.payload.host_host == 'homelab01.lcs.local' and
        event.payload.operation_data is match("^Space used: 9", ignorecase=true) 
      action:
        run_job_template:
          name: "My first playbook"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"