---
- name: Zabbix Test rulebook
  hosts: EDA
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5015

  rules:
  
    # - name: debug
    #   condition: event.payload
    #   action:
    #     debug:  
    #       msg: "Event received: {{ event.payload.event_name }}"
    
    - name: Motor de regras
      condition: event.payload.event_name is search("Service is not running", ignorecase=true)
      action:
        run_job_template:
          name: "Orizon"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"
              service: "{{ event.payload.event_name.split(':')[1] | trim }}"
    
    - name: File system
      condition: event.payload.event_name is search("Space is critically low", ignorecase=true)
      action:
        run_job_template:
          name: "Orizon"
          organization: "Default"
          job_args:
            extra_vars:
              server: "{{ event.payload.host_ip }}"
              dir: "{{ event.payload.filesystem[0] }}"